In [ ]:
#run in virtual env called '3DED' on Erebor

In [71]:
%matplotlib qt
import hyperspy.api as hs
import hyperspy.io_plugins.mrc
import pyxem as pxm
import numpy as np
import mrcfile
import os
import matplotlib.pyplot as plt
import tiffile
from PIL import Image

In [ ]:
#.mrc data is widely used as the format for tomographic data

In [79]:
#choose the sub folder which contains the mrc files
data_origin_folder = 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh'
sub_folder = '\\bismuth_susalicylate_B_20191124_175237'

data_origin_folder = data_origin_folder + sub_folder
print(data_origin_folder)

#folder to write the tifs to
destination_folder = "E:\\hl585\\duncan_data_processed\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237"

F:\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237


In [80]:
filenames = []
print(data_origin_folder)
for root, dirs, files in os.walk(data_origin_folder):
    for file in files:
        if file.endswith(".mrc"):
             filenames.append(os.path.join(root, file))

filenames = np.sort(filenames)

print(filenames)

F:\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237
['F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0000.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0001.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0002.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0003.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0004.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191124_175237\\2019-11-24-175724\\2019-11-24-175724_0005.mrc'
 'F:\\3ded_kenneth_harris_samples\\191123_med_kdmh\\bismuth_susalicylate_B_20191

In [68]:
#test cell: don't actually run in the real thing!
file = filenames[150]
file_path = file[78:-4]
print(file[78:-4])
parent_folder = file[78:-27]
print(parent_folder)
os.mkdir(destination_folder + '\\' + parent_folder)

\2019-11-24-122205\2019-11-24-122205_0008
\2019-11-24-122205


In [ ]:
#data = hyperspy.io_plugins.mrc.file_reader(file, endianess='<')#, **kwds)
#data = hs.load(file, mmap_mode)

In [89]:
for file in filenames:
    file_path = file[86:-4]
    print(file_path)
    parent_folder = file[86:-27]
    print(parent_folder)
    
    destination_parent_folder = destination_folder + '\\' + parent_folder
    print(destination_parent_folder)
    if not os.path.exists(destination_parent_folder):
        os.mkdir(destination_parent_folder)
    with mrcfile.open(file) as mrc:
        print(mrc.data)
        numpy = mrc.data
        print(numpy)
        im= Image.fromarray(numpy)
        save_path = destination_folder + '\\'+ file_path + '.tif'
        print(save_path)
        im.save(destination_folder + '\\' + file_path + '.tif')

2019-11-24-175724\2019-11-24-175724_0000
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -3  -4  -4 ... -10  -4 -10]
 [ -4  -4  -4 ...  -6  -9  -6]
 [ -4  -4  -4 ...  -5 -10 -13]
 ...
 [ -5  -5  -5 ... -14 -11 -20]
 [ -5  -6  -6 ... -14 -15 -18]
 [ -6  -6  -6 ... -12  -4 -10]]
[[ -3  -4  -4 ... -10  -4 -10]
 [ -4  -4  -4 ...  -6  -9  -6]
 [ -4  -4  -4 ...  -5 -10 -13]
 ...
 [ -5  -5  -5 ... -14 -11 -20]
 [ -5  -6  -6 ... -14 -15 -18]
 [ -6  -6  -6 ... -12  -4 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0000.tif
2019-11-24-175724\2019-11-24-175724_0001
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -1  -1   0 ... -13  -5 -13]
 [ -2  -1  -1 ... -10 -18 -11]
 [ -2  -2  -2

2019-11-24-175724\2019-11-24-175724_0012
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -2  -2  -2 ...   0   2  -5]
 [ -3  -3  -2 ... -12 -14  -9]
 [ -3  -3  -3 ... -12 -15 -11]
 ...
 [ -7  -7  -7 ... -11  -6 -18]
 [ -7  -7  -7 ... -16 -13 -19]
 [ -7  -7  -7 ...   0  -3  -5]]
[[ -2  -2  -2 ...   0   2  -5]
 [ -3  -3  -2 ... -12 -14  -9]
 [ -3  -3  -3 ... -12 -15 -11]
 ...
 [ -7  -7  -7 ... -11  -6 -18]
 [ -7  -7  -7 ... -16 -13 -19]
 [ -7  -7  -7 ...   0  -3  -5]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0012.tif
2019-11-24-175724\2019-11-24-175724_0013
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -6  -6  -7 ... -21 -16  -1]
 [ -7  -7  -7 ...  -4 -20 -16]
 [ -6  -6  -7

2019-11-24-175724\2019-11-24-175724_0024
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -9  -9  -9 ... -11 -10 -12]
 [ -9  -9  -9 ...  -2 -23 -15]
 [ -9  -9  -9 ...  -8 -23 -14]
 ...
 [ -5  -5  -5 ...  -6  -7  -8]
 [ -6  -6  -6 ... -19 -15 -10]
 [ -6  -6  -6 ... -14   0 -13]]
[[ -9  -9  -9 ... -11 -10 -12]
 [ -9  -9  -9 ...  -2 -23 -15]
 [ -9  -9  -9 ...  -8 -23 -14]
 ...
 [ -5  -5  -5 ...  -6  -7  -8]
 [ -6  -6  -6 ... -19 -15 -10]
 [ -6  -6  -6 ... -14   0 -13]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0024.tif
2019-11-24-175724\2019-11-24-175724_0025
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -8  -8  -9 ...  -7   0 -10]
 [ -9  -9  -9 ... -10 -16 -19]
 [ -8  -8  -8

2019-11-24-175724\2019-11-24-175724_0036
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -7  -7  -7 ... -11   0  -5]
 [ -7  -7  -7 ...   5 -18 -20]
 [ -7  -7  -7 ...  -5 -13 -21]
 ...
 [ -6  -6  -6 ... -17 -12 -18]
 [ -6  -6  -7 ... -12 -13 -16]
 [ -7  -7  -7 ...  -6  -6  -9]]
[[ -7  -7  -7 ... -11   0  -5]
 [ -7  -7  -7 ...   5 -18 -20]
 [ -7  -7  -7 ...  -5 -13 -21]
 ...
 [ -6  -6  -6 ... -17 -12 -18]
 [ -6  -6  -7 ... -12 -13 -16]
 [ -7  -7  -7 ...  -6  -6  -9]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0036.tif
2019-11-24-175724\2019-11-24-175724_0037
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -5  -6  -6 ... -17 -10  -9]
 [ -6  -6  -6 ... -20 -18  -5]
 [ -6  -6  -6

2019-11-24-175724\2019-11-24-175724_0048
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -2  -1  -1 ... -11  -4  -5]
 [ -2  -2  -2 ...  -1 -16  -8]
 [ -2  -3  -3 ... -17 -21 -14]
 ...
 [ -8  -8  -8 ... -21 -11 -21]
 [ -8  -8  -8 ... -19 -14 -12]
 [ -8  -8  -8 ...  -6 -15 -10]]
[[ -2  -1  -1 ... -11  -4  -5]
 [ -2  -2  -2 ...  -1 -16  -8]
 [ -2  -3  -3 ... -17 -21 -14]
 ...
 [ -8  -8  -8 ... -21 -11 -21]
 [ -8  -8  -8 ... -19 -14 -12]
 [ -8  -8  -8 ...  -6 -15 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0048.tif
2019-11-24-175724\2019-11-24-175724_0049
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -5  -5  -5 ...  -8   2  -4]
 [ -5  -5  -5 ...  -7 -19 -13]
 [ -6  -5  -5

2019-11-24-175724\2019-11-24-175724_0060
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -6  -5  -5 ... -18  -2 -15]
 [ -6  -6  -6 ...  -9 -16 -20]
 [ -6  -6  -6 ... -14 -13 -18]
 ...
 [ -7  -7  -7 ...  -5  -5 -18]
 [ -7  -7  -7 ... -14 -12 -15]
 [ -7  -7  -8 ... -18  -9 -18]]
[[ -6  -5  -5 ... -18  -2 -15]
 [ -6  -6  -6 ...  -9 -16 -20]
 [ -6  -6  -6 ... -14 -13 -18]
 ...
 [ -7  -7  -7 ...  -5  -5 -18]
 [ -7  -7  -7 ... -14 -12 -15]
 [ -7  -7  -8 ... -18  -9 -18]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0060.tif
2019-11-24-175724\2019-11-24-175724_0061
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -6  -6  -7 ...  -7  -6 -14]
 [ -6  -7  -7 ...  -2 -13  -8]
 [ -6  -6  -7

2019-11-24-175724\2019-11-24-175724_0072
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -4  -4  -5 ...  -4  13 -10]
 [ -5  -5  -5 ...   0 -20 -10]
 [ -5  -5  -5 ... -10 -10  -9]
 ...
 [ -6  -6  -6 ... -13   0 -14]
 [ -6  -6  -6 ... -13 -17 -19]
 [ -6  -6  -6 ... -14 -10 -17]]
[[ -4  -4  -5 ...  -4  13 -10]
 [ -5  -5  -5 ...   0 -20 -10]
 [ -5  -5  -5 ... -10 -10  -9]
 ...
 [ -6  -6  -6 ... -13   0 -14]
 [ -6  -6  -6 ... -13 -17 -19]
 [ -6  -6  -6 ... -14 -10 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0072.tif
2019-11-24-175724\2019-11-24-175724_0073
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -1  -1  -1 ...  -6   5 -15]
 [ -2  -1  -1 ...   1 -18 -19]
 [ -1  -1  -1

2019-11-24-175724\2019-11-24-175724_0084
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[  0   0   0 ... -12  -5  -8]
 [  0   0   0 ...  -8 -17 -10]
 [  0  -1  -1 ...  -6 -10 -11]
 ...
 [ -5  -5  -5 ... -18 -10 -16]
 [ -6  -6  -6 ... -13 -15 -19]
 [ -6  -6  -6 ...   3  -8  -6]]
[[  0   0   0 ... -12  -5  -8]
 [  0   0   0 ...  -8 -17 -10]
 [  0  -1  -1 ...  -6 -10 -11]
 ...
 [ -5  -5  -5 ... -18 -10 -16]
 [ -6  -6  -6 ... -13 -15 -19]
 [ -6  -6  -6 ...   3  -8  -6]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0084.tif
2019-11-24-175724\2019-11-24-175724_0085
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -7  -7  -7 ...  -8   0  -7]
 [ -7  -7  -7 ...   1 -12  -8]
 [ -7  -7  -7

2019-11-24-175724\2019-11-24-175724_0096
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -5  -5  -5 ... -10   4 -10]
 [ -6  -6  -5 ...  -6 -15 -12]
 [ -6  -6  -6 ... -13 -22 -16]
 ...
 [ -8  -8  -8 ... -13 -21 -22]
 [ -9  -9  -9 ... -11 -12 -14]
 [ -9  -9  -9 ... -16 -10 -20]]
[[ -5  -5  -5 ... -10   4 -10]
 [ -6  -6  -5 ...  -6 -15 -12]
 [ -6  -6  -6 ... -13 -22 -16]
 ...
 [ -8  -8  -8 ... -13 -21 -22]
 [ -9  -9  -9 ... -11 -12 -14]
 [ -9  -9  -9 ... -16 -10 -20]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724\2019-11-24-175724_0096.tif
2019-11-24-175724\2019-11-24-175724_0097
2019-11-24-175724
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-175724
[[ -4  -4  -4 ... -15  -6 -24]
 [ -5  -5  -5 ...   1 -15  -9]
 [ -5  -5  -5

2019-11-24-180603\2019-11-24-180603_0007
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -7  -7  -7 ...  -7   2   1]
 [ -6  -7  -7 ... -13  -2   7]
 [ -6  -6  -6 ...  -5 -14  -6]
 ...
 [  3   3   3 ...   0 -15  -1]
 [  3   3   2 ...  -6  -6  -9]
 [  3   2   2 ...   4  -5 -10]]
[[ -7  -7  -7 ...  -7   2   1]
 [ -6  -7  -7 ... -13  -2   7]
 [ -6  -6  -6 ...  -5 -14  -6]
 ...
 [  3   3   3 ...   0 -15  -1]
 [  3   3   2 ...  -6  -6  -9]
 [  3   2   2 ...   4  -5 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0007.tif
2019-11-24-180603\2019-11-24-180603_0008
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -6  -6  -6 ...  -4  -1   7]
 [ -6  -6  -6 ... -15  -5  -1]
 [ -6  -6  -6

2019-11-24-180603\2019-11-24-180603_0019
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -2  -2  -2 ...   0   6   1]
 [ -2  -2  -2 ...  -5  -5  -4]
 [ -3  -3  -2 ...  -5 -11  -4]
 ...
 [  3   3   3 ...  -9 -11  -7]
 [  2   2   2 ... -10  -6 -10]
 [  2   2   2 ...  -5   3  -6]]
[[ -2  -2  -2 ...   0   6   1]
 [ -2  -2  -2 ...  -5  -5  -4]
 [ -3  -3  -2 ...  -5 -11  -4]
 ...
 [  3   3   3 ...  -9 -11  -7]
 [  2   2   2 ... -10  -6 -10]
 [  2   2   2 ...  -5   3  -6]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0019.tif
2019-11-24-180603\2019-11-24-180603_0020
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  2   2   2 ... -10 -10   2]
 [  2   2   2 ... -13 -12 -12]
 [  1   1   1

2019-11-24-180603\2019-11-24-180603_0031
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -1  -1  -1 ...  -2   2   6]
 [ -1  -1  -1 ...  -8 -11  -4]
 [ -1  -1  -1 ...   4 -12  -6]
 ...
 [  2   2   2 ...   5  -9  -9]
 [  3   3   3 ...  -9  -4  -1]
 [  3   3   2 ...  -4  -3 -11]]
[[ -1  -1  -1 ...  -2   2   6]
 [ -1  -1  -1 ...  -8 -11  -4]
 [ -1  -1  -1 ...   4 -12  -6]
 ...
 [  2   2   2 ...   5  -9  -9]
 [  3   3   3 ...  -9  -4  -1]
 [  3   3   2 ...  -4  -3 -11]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0031.tif
2019-11-24-180603\2019-11-24-180603_0032
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  5   5   5 ...  -7   1   8]
 [  5   5   5 ...  -6  -2  -7]
 [  5   5   5

2019-11-24-180603\2019-11-24-180603_0043
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  0  -1  -1 ...  -9  -7   5]
 [  0   0   0 ... -15 -10  -4]
 [  0   0   0 ...  -5 -13  -3]
 ...
 [  1   1   1 ...  -8 -11  -8]
 [  1   1   1 ... -13 -13 -11]
 [  1   1   1 ... -10  -2  -8]]
[[  0  -1  -1 ...  -9  -7   5]
 [  0   0   0 ... -15 -10  -4]
 [  0   0   0 ...  -5 -13  -3]
 ...
 [  1   1   1 ...  -8 -11  -8]
 [  1   1   1 ... -13 -13 -11]
 [  1   1   1 ... -10  -2  -8]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0043.tif
2019-11-24-180603\2019-11-24-180603_0044
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -4  -4  -5 ...  -6   1  -5]
 [ -3  -4  -4 ...  -3  -7  -5]
 [ -3  -3  -3

2019-11-24-180603\2019-11-24-180603_0055
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -6  -6  -6 ...   2  -5   3]
 [ -6  -6  -6 ...  -9   0   2]
 [ -6  -6  -6 ...   0 -10  -6]
 ...
 [  5   5   5 ...   5 -18  -1]
 [  5   5   5 ...  -4   0   1]
 [  5   4   4 ...  -3  10   1]]
[[ -6  -6  -6 ...   2  -5   3]
 [ -6  -6  -6 ...  -9   0   2]
 [ -6  -6  -6 ...   0 -10  -6]
 ...
 [  5   5   5 ...   5 -18  -1]
 [  5   5   5 ...  -4   0   1]
 [  5   4   4 ...  -3  10   1]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0055.tif
2019-11-24-180603\2019-11-24-180603_0056
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -4  -4  -4 ... -10  -3  16]
 [ -4  -4  -4 ... -18 -12  -3]
 [ -5  -5  -5

2019-11-24-180603\2019-11-24-180603_0067
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  1   1   1 ...   0  -7  10]
 [  1   1   1 ... -10  -9  -1]
 [  1   1   1 ...  -5 -18  -6]
 ...
 [  1   1   1 ...  -7 -17  -7]
 [  1   1   1 ...  -9  -5  -9]
 [  1   1   1 ...  -9  -3 -15]]
[[  1   1   1 ...   0  -7  10]
 [  1   1   1 ... -10  -9  -1]
 [  1   1   1 ...  -5 -18  -6]
 ...
 [  1   1   1 ...  -7 -17  -7]
 [  1   1   1 ...  -9  -5  -9]
 [  1   1   1 ...  -9  -3 -15]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0067.tif
2019-11-24-180603\2019-11-24-180603_0068
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  0   0   0 ...  -4  -7  -2]
 [  0   0   0 ... -20  -8 -14]
 [  0   0   0

2019-11-24-180603\2019-11-24-180603_0079
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[  1   1   2 ...  -5   0  -1]
 [  1   1   2 ... -20  -5 -14]
 [  2   2   2 ...  -2 -18  -6]
 ...
 [  1   1   1 ...  -1 -10  -3]
 [  1   1   0 ...  -7 -14  -8]
 [  1   1   0 ...   1  -5  -9]]
[[  1   1   2 ...  -5   0  -1]
 [  1   1   2 ... -20  -5 -14]
 [  2   2   2 ...  -2 -18  -6]
 ...
 [  1   1   1 ...  -1 -10  -3]
 [  1   1   0 ...  -7 -14  -8]
 [  1   1   0 ...   1  -5  -9]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0079.tif
2019-11-24-180603\2019-11-24-180603_0080
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -3  -3  -4 ...   0   0  -1]
 [ -3  -4  -4 ...  -2  -5  -8]
 [ -3  -3  -4

2019-11-24-180603\2019-11-24-180603_0091
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -1  -1  -1 ...   5  -2   0]
 [  0  -1  -1 ...  -1 -10  -9]
 [  0   0   0 ...  -6 -20  -7]
 ...
 [  1   1   1 ...   1 -12 -12]
 [  1   1   1 ... -11  -5   3]
 [  1   1   0 ...   3  -3  -4]]
[[ -1  -1  -1 ...   5  -2   0]
 [  0  -1  -1 ...  -1 -10  -9]
 [  0   0   0 ...  -6 -20  -7]
 ...
 [  1   1   1 ...   1 -12 -12]
 [  1   1   1 ... -11  -5   3]
 [  1   1   0 ...   3  -3  -4]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603\2019-11-24-180603_0091.tif
2019-11-24-180603\2019-11-24-180603_0092
2019-11-24-180603
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-180603
[[ -8  -8  -8 ...  -1  -1  -4]
 [ -7  -8  -8 ... -12 -10 -12]
 [ -6  -7  -7

2019-11-24-181127\2019-11-24-181127_0002
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -2 ...   4   6  -3]
 [ -1  -1  -1 ... -14  -5 -15]
 [  0  -1  -1 ...  -1 -10 -11]
 ...
 [  2   2   2 ...  -5 -17  -1]
 [  2   2   3 ...  -7 -20  -5]
 [  2   2   2 ...  -9   3 -15]]
[[ -2  -2  -2 ...   4   6  -3]
 [ -1  -1  -1 ... -14  -5 -15]
 [  0  -1  -1 ...  -1 -10 -11]
 ...
 [  2   2   2 ...  -5 -17  -1]
 [  2   2   3 ...  -7 -20  -5]
 [  2   2   2 ...  -9   3 -15]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0002.tif
2019-11-24-181127\2019-11-24-181127_0003
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -5  -6  -6 ...  -9 -10  -7]
 [ -5  -6  -6 ... -21  -8 -20]
 [ -5  -5  -5

2019-11-24-181127\2019-11-24-181127_0014
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -2 ... -11  -4   1]
 [ -1  -2  -2 ...  -9  -2 -11]
 [ -1  -1  -1 ...   5 -13 -15]
 ...
 [  0   0   0 ...   2  -6  -9]
 [  0   0   0 ... -14 -20 -16]
 [  0   0   0 ... -16  -3 -17]]
[[ -2  -2  -2 ... -11  -4   1]
 [ -1  -2  -2 ...  -9  -2 -11]
 [ -1  -1  -1 ...   5 -13 -15]
 ...
 [  0   0   0 ...   2  -6  -9]
 [  0   0   0 ... -14 -20 -16]
 [  0   0   0 ... -16  -3 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0014.tif
2019-11-24-181127\2019-11-24-181127_0015
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -5  -5  -6 ...  -4   0 -15]
 [ -4  -5  -5 ... -11  -5 -13]
 [ -4  -4  -4

2019-11-24-181127\2019-11-24-181127_0026
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -2 ... -11 -10  -8]
 [ -2  -2  -2 ...  -9   6 -20]
 [ -1  -1  -1 ...   6  -6 -11]
 ...
 [  3   3   3 ...  -5  -8  -9]
 [  3   3   3 ... -17 -14  -6]
 [  3   3   3 ...   0   6  -8]]
[[ -2  -2  -2 ... -11 -10  -8]
 [ -2  -2  -2 ...  -9   6 -20]
 [ -1  -1  -1 ...   6  -6 -11]
 ...
 [  3   3   3 ...  -5  -8  -9]
 [  3   3   3 ... -17 -14  -6]
 [  3   3   3 ...   0   6  -8]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0026.tif
2019-11-24-181127\2019-11-24-181127_0027
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -6  -6  -6 ...  -3 -10   0]
 [ -6  -6  -6 ... -14   0  -9]
 [ -5  -5  -5

2019-11-24-181127\2019-11-24-181127_0038
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -3 ... -11   0  -5]
 [ -2  -2  -2 ... -17  -5 -14]
 [ -1  -1  -1 ...   4 -11 -15]
 ...
 [ -2  -2  -2 ...   1  -4  -9]
 [ -2  -2  -2 ...  -9 -13  -7]
 [ -3  -3  -3 ...  -5  -8  -3]]
[[ -2  -2  -3 ... -11   0  -5]
 [ -2  -2  -2 ... -17  -5 -14]
 [ -1  -1  -1 ...   4 -11 -15]
 ...
 [ -2  -2  -2 ...   1  -4  -9]
 [ -2  -2  -2 ...  -9 -13  -7]
 [ -3  -3  -3 ...  -5  -8  -3]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0038.tif
2019-11-24-181127\2019-11-24-181127_0039
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -3 ...  -5 -10   0]
 [ -2  -2  -2 ...  -6 -12  -1]
 [ -1  -1  -1

2019-11-24-181127\2019-11-24-181127_0050
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -3  -3  -3 ...  -1   3  -5]
 [ -3  -3  -3 ... -14   0  -9]
 [ -2  -2  -2 ...   6 -10 -15]
 ...
 [  0   0   0 ...   0  -6  -9]
 [  0   0   0 ... -10 -15 -15]
 [ -1  -1  -1 ...   0   5 -11]]
[[ -3  -3  -3 ...  -1   3  -5]
 [ -3  -3  -3 ... -14   0  -9]
 [ -2  -2  -2 ...   6 -10 -15]
 ...
 [  0   0   0 ...   0  -6  -9]
 [  0   0   0 ... -10 -15 -15]
 [ -1  -1  -1 ...   0   5 -11]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0050.tif
2019-11-24-181127\2019-11-24-181127_0051
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -1  -1  -2 ...   1  -2   0]
 [ -1  -1  -1 ...  -6  -3 -13]
 [  0  -1  -1

2019-11-24-181127\2019-11-24-181127_0062
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -5  -5  -6 ... -15  -9  -5]
 [ -5  -5  -5 ... -13  -9 -15]
 [ -5  -5  -5 ...   0 -15  -7]
 ...
 [  0   0   0 ...   0  -9 -16]
 [  1   1   1 ... -11 -17 -10]
 [  1   1   1 ...  -9  10 -14]]
[[ -5  -5  -6 ... -15  -9  -5]
 [ -5  -5  -5 ... -13  -9 -15]
 [ -5  -5  -5 ...   0 -15  -7]
 ...
 [  0   0   0 ...   0  -9 -16]
 [  1   1   1 ... -11 -17 -10]
 [  1   1   1 ...  -9  10 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0062.tif
2019-11-24-181127\2019-11-24-181127_0063
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[  2   2   2 ...   1  -3  -8]
 [  2   2   2 ... -17  -3 -17]
 [  3   2   2

2019-11-24-181127\2019-11-24-181127_0074
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[  0   0   0 ...  10  -6  -3]
 [  0   0   0 ...  -5  -4 -12]
 [  1   1   1 ...   6  -3  -8]
 ...
 [  3   3   3 ...   3 -11  -7]
 [  3   3   3 ... -11 -16  -5]
 [  3   3   3 ...  -8  -8 -14]]
[[  0   0   0 ...  10  -6  -3]
 [  0   0   0 ...  -5  -4 -12]
 [  1   1   1 ...   6  -3  -8]
 ...
 [  3   3   3 ...   3 -11  -7]
 [  3   3   3 ... -11 -16  -5]
 [  3   3   3 ...  -8  -8 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0074.tif
2019-11-24-181127\2019-11-24-181127_0075
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -7  -8  -8 ...  -7  -4  -5]
 [ -7  -7  -8 ...  -5 -10  -4]
 [ -6  -6  -6

2019-11-24-181127\2019-11-24-181127_0086
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -8  -8  -8 ...   1  -2  -4]
 [ -8  -8  -8 ... -12 -17 -18]
 [ -7  -7  -7 ...  12 -10 -14]
 ...
 [ -5  -5  -5 ...  -3  -9  -5]
 [ -4  -4  -4 ...  -9 -15 -14]
 [ -4  -4  -4 ... -10   0 -21]]
[[ -8  -8  -8 ...   1  -2  -4]
 [ -8  -8  -8 ... -12 -17 -18]
 [ -7  -7  -7 ...  12 -10 -14]
 ...
 [ -5  -5  -5 ...  -3  -9  -5]
 [ -4  -4  -4 ...  -9 -15 -14]
 [ -4  -4  -4 ... -10   0 -21]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0086.tif
2019-11-24-181127\2019-11-24-181127_0087
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -3  -3 ...   0  -7 -10]
 [ -2  -2  -3 ... -12  -7 -10]
 [ -1  -2  -2

2019-11-24-181127\2019-11-24-181127_0098
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -2 ...   6   0  -8]
 [ -2  -2  -2 ...   0  -3  -6]
 [ -2  -2  -2 ...   4 -11  -7]
 ...
 [  2   2   2 ...   5 -16  -5]
 [  2   2   2 ... -17 -19  -6]
 [  2   2   2 ... -23  -8 -10]]
[[ -2  -2  -2 ...   6   0  -8]
 [ -2  -2  -2 ...   0  -3  -6]
 [ -2  -2  -2 ...   4 -11  -7]
 ...
 [  2   2   2 ...   5 -16  -5]
 [  2   2   2 ... -17 -19  -6]
 [  2   2   2 ... -23  -8 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127\2019-11-24-181127_0098.tif
2019-11-24-181127\2019-11-24-181127_0099
2019-11-24-181127
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-181127
[[ -2  -2  -3 ...   0   0   4]
 [ -2  -2  -2 ... -11  -4 -19]
 [ -2  -2  -2

2019-11-24-182044\2019-11-24-182044_0009
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -7  -8  -8 ...  -4  -4 -12]
 [ -7  -7  -7 ...  -9  -8   3]
 [ -7  -7  -7 ...  -9  -9  -2]
 ...
 [ -1  -1   0 ...  -6  -5 -14]
 [  0   0   0 ...  -9  -2 -10]
 [  0   0   0 ...  -4  -4 -17]]
[[ -7  -8  -8 ...  -4  -4 -12]
 [ -7  -7  -7 ...  -9  -8   3]
 [ -7  -7  -7 ...  -9  -9  -2]
 ...
 [ -1  -1   0 ...  -6  -5 -14]
 [  0   0   0 ...  -9  -2 -10]
 [  0   0   0 ...  -4  -4 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0009.tif
2019-11-24-182044\2019-11-24-182044_0010
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -4  -4  -4 ...  -8  -3  -9]
 [ -4  -4  -4 ... -20 -22  -5]
 [ -4  -4  -4

2019-11-24-182044\2019-11-24-182044_0021
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[  2   2   2 ...  -4  10  -9]
 [  2   2   2 ...  -5 -11  -3]
 [  1   1   2 ...   0  -6   0]
 ...
 [  1   1   1 ... -11  -9 -16]
 [  1   1   1 ...  -5 -10 -14]
 [  1   1   1 ...  -4 -10 -20]]
[[  2   2   2 ...  -4  10  -9]
 [  2   2   2 ...  -5 -11  -3]
 [  1   1   2 ...   0  -6   0]
 ...
 [  1   1   1 ... -11  -9 -16]
 [  1   1   1 ...  -5 -10 -14]
 [  1   1   1 ...  -4 -10 -20]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0021.tif
2019-11-24-182044\2019-11-24-182044_0022
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[-10 -10 -10 ... -17   0  -5]
 [-10 -10 -10 ... -21 -20 -15]
 [-10 -10 -10

2019-11-24-182044\2019-11-24-182044_0033
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[  2   2   2 ...  -8 -10 -13]
 [  2   2   2 ...  -8 -18  -8]
 [  2   2   2 ...  -7 -10  -7]
 ...
 [ -1  -1  -1 ...  -4  -8 -12]
 [  0  -1   0 ...  -7  -7 -15]
 [  0   0   0 ...  -5  -3 -14]]
[[  2   2   2 ...  -8 -10 -13]
 [  2   2   2 ...  -8 -18  -8]
 [  2   2   2 ...  -7 -10  -7]
 ...
 [ -1  -1  -1 ...  -4  -8 -12]
 [  0  -1   0 ...  -7  -7 -15]
 [  0   0   0 ...  -5  -3 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0033.tif
2019-11-24-182044\2019-11-24-182044_0034
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -6  -6  -6 ...  -5   5  -7]
 [ -6  -6  -6 ...  -6 -10  -5]
 [ -6  -6  -6

2019-11-24-182044\2019-11-24-182044_0045
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -4  -5  -5 ...  -2   1 -16]
 [ -5  -5  -5 ...  -7 -19 -12]
 [ -5  -5  -5 ...  -5 -13   0]
 ...
 [  2   2   2 ... -14 -12  -7]
 [  2   2   2 ... -15  -4 -17]
 [  3   2   2 ... -14 -10 -17]]
[[ -4  -5  -5 ...  -2   1 -16]
 [ -5  -5  -5 ...  -7 -19 -12]
 [ -5  -5  -5 ...  -5 -13   0]
 ...
 [  2   2   2 ... -14 -12  -7]
 [  2   2   2 ... -15  -4 -17]
 [  3   2   2 ... -14 -10 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0045.tif
2019-11-24-182044\2019-11-24-182044_0046
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[  0   0   0 ... -11  -3   7]
 [  0   0   0 ...  -9 -20  -4]
 [  0   0   0

2019-11-24-182044\2019-11-24-182044_0057
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -5  -5  -5 ...  -4  -8  -5]
 [ -5  -5  -5 ...  -5 -18  -6]
 [ -6  -6  -5 ...  -6  -8   0]
 ...
 [ -1  -1  -1 ...  -8  -5  -6]
 [  0  -1  -1 ... -14  -1  -5]
 [  0  -1  -1 ...  -9  -3  -8]]
[[ -5  -5  -5 ...  -4  -8  -5]
 [ -5  -5  -5 ...  -5 -18  -6]
 [ -6  -6  -5 ...  -6  -8   0]
 ...
 [ -1  -1  -1 ...  -8  -5  -6]
 [  0  -1  -1 ... -14  -1  -5]
 [  0  -1  -1 ...  -9  -3  -8]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0057.tif
2019-11-24-182044\2019-11-24-182044_0058
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -4  -4  -4 ...  -5  -6 -15]
 [ -4  -4  -4 ...  -8 -17 -14]
 [ -4  -4  -4

2019-11-24-182044\2019-11-24-182044_0069
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -5  -5  -5 ...  -9 -10 -21]
 [ -5  -5  -5 ...  -3 -22  -6]
 [ -5  -5  -5 ...  -4 -11  -6]
 ...
 [  2   1   1 ...  -4  -7 -14]
 [  1   1   1 ... -11  -8 -10]
 [  1   1   1 ...   7  -5 -11]]
[[ -5  -5  -5 ...  -9 -10 -21]
 [ -5  -5  -5 ...  -3 -22  -6]
 [ -5  -5  -5 ...  -4 -11  -6]
 ...
 [  2   1   1 ...  -4  -7 -14]
 [  1   1   1 ... -11  -8 -10]
 [  1   1   1 ...   7  -5 -11]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0069.tif
2019-11-24-182044\2019-11-24-182044_0070
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -3  -3  -2 ...  -7   0 -11]
 [ -3  -3  -3 ...  -5 -10  -3]
 [ -3  -3  -3

2019-11-24-182044\2019-11-24-182044_0081
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -5  -5  -5 ...  -6  -8 -17]
 [ -5  -5  -5 ... -11  -7 -12]
 [ -4  -4  -5 ...  -5  -4   3]
 ...
 [  4   4   4 ... -15  -4  -5]
 [  4   4   4 ... -11  -4 -11]
 [  4   4   4 ...   7   1 -12]]
[[ -5  -5  -5 ...  -6  -8 -17]
 [ -5  -5  -5 ... -11  -7 -12]
 [ -4  -4  -5 ...  -5  -4   3]
 ...
 [  4   4   4 ... -15  -4  -5]
 [  4   4   4 ... -11  -4 -11]
 [  4   4   4 ...   7   1 -12]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0081.tif
2019-11-24-182044\2019-11-24-182044_0082
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -5  -5  -5 ...  -8 -10 -13]
 [ -6  -6  -5 ... -14 -16  -8]
 [ -6  -6  -6

2019-11-24-182044\2019-11-24-182044_0093
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[ -7  -7  -7 ...  -5  -3   2]
 [ -7  -7  -7 ... -15 -18   0]
 [ -7  -7  -7 ...  -5  -9   0]
 ...
 [ -2  -2  -2 ...  -7  -5  -5]
 [ -2  -2  -2 ...  -7 -10 -11]
 [ -2  -2  -2 ...  -3 -11  -5]]
[[ -7  -7  -7 ...  -5  -3   2]
 [ -7  -7  -7 ... -15 -18   0]
 [ -7  -7  -7 ...  -5  -9   0]
 ...
 [ -2  -2  -2 ...  -7  -5  -5]
 [ -2  -2  -2 ...  -7 -10 -11]
 [ -2  -2  -2 ...  -3 -11  -5]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044\2019-11-24-182044_0093.tif
2019-11-24-182044\2019-11-24-182044_0094
2019-11-24-182044
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-182044
[[  1   1   1 ...  -1 -10  -2]
 [  1   1   1 ... -14 -10  -6]
 [  1   1   1

2019-11-24-184347\2019-11-24-184347_0004
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -3  -3  -3 ...  -5 -24 -25]
 [ -3  -3  -3 ... -19 -15 -14]
 [ -3  -3  -3 ... -15 -15  -4]
 ...
 [ -5  -5  -5 ... -17 -10 -12]
 [ -5  -5  -5 ...   2  -7 -15]
 [ -6  -6  -5 ...  -8 -13 -17]]
[[ -3  -3  -3 ...  -5 -24 -25]
 [ -3  -3  -3 ... -19 -15 -14]
 [ -3  -3  -3 ... -15 -15  -4]
 ...
 [ -5  -5  -5 ... -17 -10 -12]
 [ -5  -5  -5 ...   2  -7 -15]
 [ -6  -6  -5 ...  -8 -13 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0004.tif
2019-11-24-184347\2019-11-24-184347_0005
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[  1   1   1 ...  -2 -18 -19]
 [  1   1   1 ... -14 -13 -12]
 [  2   1   1

2019-11-24-184347\2019-11-24-184347_0016
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -6  -6  -6 ...  -6 -10 -13]
 [ -6  -6  -6 ... -12 -15  -5]
 [ -6  -6  -6 ... -11  -5 -11]
 ...
 [ -4  -4  -4 ...  -7 -12  -6]
 [ -4  -3  -3 ...  -9  -8 -14]
 [ -3  -3  -3 ... -10   0  -4]]
[[ -6  -6  -6 ...  -6 -10 -13]
 [ -6  -6  -6 ... -12 -15  -5]
 [ -6  -6  -6 ... -11  -5 -11]
 ...
 [ -4  -4  -4 ...  -7 -12  -6]
 [ -4  -3  -3 ...  -9  -8 -14]
 [ -3  -3  -3 ... -10   0  -4]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0016.tif
2019-11-24-184347\2019-11-24-184347_0017
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -2  -2  -2 ...  -5 -20 -20]
 [ -2  -2  -2 ... -17  -9 -19]
 [ -2  -2  -2

2019-11-24-184347\2019-11-24-184347_0028
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -5  -5  -5 ...  -5 -21 -27]
 [ -5  -5  -5 ... -19 -20  -9]
 [ -5  -5  -5 ... -14  -8  -4]
 ...
 [ -5  -5  -5 ... -14  -8 -11]
 [ -5  -5  -4 ...  -7  -8 -22]
 [ -4  -4  -4 ... -14 -10 -13]]
[[ -5  -5  -5 ...  -5 -21 -27]
 [ -5  -5  -5 ... -19 -20  -9]
 [ -5  -5  -5 ... -14  -8  -4]
 ...
 [ -5  -5  -5 ... -14  -8 -11]
 [ -5  -5  -4 ...  -7  -8 -22]
 [ -4  -4  -4 ... -14 -10 -13]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0028.tif
2019-11-24-184347\2019-11-24-184347_0029
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -3  -3  -3 ...  -8 -20 -12]
 [ -3  -3  -3 ... -20 -17 -13]
 [ -3  -3  -3

2019-11-24-184347\2019-11-24-184347_0040
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -4  -5  -5 ...   0 -19 -17]
 [ -4  -4  -5 ... -16 -14   3]
 [ -4  -4  -4 ...  -3  -8  -6]
 ...
 [ -7  -7  -7 ... -15  -6  -9]
 [ -8  -8  -8 ... -11  -8 -14]
 [ -7  -7  -7 ... -13  -9  -7]]
[[ -4  -5  -5 ...   0 -19 -17]
 [ -4  -4  -5 ... -16 -14   3]
 [ -4  -4  -4 ...  -3  -8  -6]
 ...
 [ -7  -7  -7 ... -15  -6  -9]
 [ -8  -8  -8 ... -11  -8 -14]
 [ -7  -7  -7 ... -13  -9  -7]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0040.tif
2019-11-24-184347\2019-11-24-184347_0041
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[  1   1   1 ... -11 -20 -22]
 [  1   1   1 ... -19 -13 -12]
 [  1   1   1

 [ -6  -6  -6 ... -10  -6 -12]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0052.tif
2019-11-24-184347\2019-11-24-184347_0053
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -1  -1  -1 ...  -4 -22  -7]
 [ -1  -1  -1 ... -19 -11 -13]
 [ -1  -1  -1 ... -16  -7 -22]
 ...
 [ -5  -5  -5 ... -10 -10  -6]
 [ -5  -5  -4 ...  -2  -4 -16]
 [ -4  -4  -4 ...  -5  -8 -22]]
[[ -1  -1  -1 ...  -4 -22  -7]
 [ -1  -1  -1 ... -19 -11 -13]
 [ -1  -1  -1 ... -16  -7 -22]
 ...
 [ -5  -5  -5 ... -10 -10  -6]
 [ -5  -5  -4 ...  -2  -4 -16]
 [ -4  -4  -4 ...  -5  -8 -22]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0053.tif
2019-11-24-184347\2019-11-24-184347_0054
2019-11-24-184347
E:\hl585\duncan_

2019-11-24-184347\2019-11-24-184347_0064
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -3  -3  -3 ... -13 -17 -27]
 [ -3  -3  -3 ... -30 -18  -1]
 [ -3  -3  -3 ... -15 -12 -19]
 ...
 [ -5  -5  -5 ... -21  -8  -3]
 [ -6  -6  -6 ...  -4 -11 -15]
 [ -6  -6  -7 ... -14  -4  -2]]
[[ -3  -3  -3 ... -13 -17 -27]
 [ -3  -3  -3 ... -30 -18  -1]
 [ -3  -3  -3 ... -15 -12 -19]
 ...
 [ -5  -5  -5 ... -21  -8  -3]
 [ -6  -6  -6 ...  -4 -11 -15]
 [ -6  -6  -7 ... -14  -4  -2]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0064.tif
2019-11-24-184347\2019-11-24-184347_0065
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -3  -3  -3 ...  -7 -15 -20]
 [ -3  -3  -3 ... -17 -18 -13]
 [ -3  -3  -3

2019-11-24-184347\2019-11-24-184347_0076
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -5  -5  -5 ...  -7 -24 -16]
 [ -5  -5  -5 ... -20 -16 -13]
 [ -6  -5  -5 ...  -8 -10  -9]
 ...
 [ -9  -9  -9 ... -19 -10  -5]
 [ -9  -9 -10 ...  -5  -9 -15]
 [-10 -10 -10 ... -18  -4 -10]]
[[ -5  -5  -5 ...  -7 -24 -16]
 [ -5  -5  -5 ... -20 -16 -13]
 [ -6  -5  -5 ...  -8 -10  -9]
 ...
 [ -9  -9  -9 ... -19 -10  -5]
 [ -9  -9 -10 ...  -5  -9 -15]
 [-10 -10 -10 ... -18  -4 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0076.tif
2019-11-24-184347\2019-11-24-184347_0077
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -4  -4  -4 ...  -8 -21 -11]
 [ -4  -4  -4 ...  -9 -19 -11]
 [ -4  -4  -4

2019-11-24-184347\2019-11-24-184347_0088
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[  2   2   2 ...  -7 -18 -13]
 [  2   2   2 ... -14 -20  -9]
 [  2   2   2 ... -10 -10 -11]
 ...
 [  1   1   1 ... -11  -3   0]
 [  1   1   1 ...   0  -2 -16]
 [  1   1   1 ... -12  -8  -7]]
[[  2   2   2 ...  -7 -18 -13]
 [  2   2   2 ... -14 -20  -9]
 [  2   2   2 ... -10 -10 -11]
 ...
 [  1   1   1 ... -11  -3   0]
 [  1   1   1 ...   0  -2 -16]
 [  1   1   1 ... -12  -8  -7]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0088.tif
2019-11-24-184347\2019-11-24-184347_0089
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -5  -5  -5 ...  -3 -23 -14]
 [ -5  -5  -5 ... -15 -16 -12]
 [ -6  -5  -5

2019-11-24-184347\2019-11-24-184347_0100
2019-11-24-184347
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347
[[ -4  -4  -3 ... -11 -19 -12]
 [ -4  -3  -3 ... -16 -14  -5]
 [ -4  -4  -3 ... -12  -8 -20]
 ...
 [ -5  -5  -5 ... -17 -11  -8]
 [ -5  -5  -5 ... -17  -7 -20]
 [ -5  -5  -5 ... -14  -9 -15]]
[[ -4  -4  -3 ... -11 -19 -12]
 [ -4  -3  -3 ... -16 -14  -5]
 [ -4  -4  -3 ... -12  -8 -20]
 ...
 [ -5  -5  -5 ... -17 -11  -8]
 [ -5  -5  -5 ... -17  -7 -20]
 [ -5  -5  -5 ... -14  -9 -15]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-184347\2019-11-24-184347_0100.tif
2019-11-24-185457\2019-11-24-185457_0000
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  4   4   4 ... -16 -11  -6]
 [  4   4   4 ... -17  -3  -5]
 [  4   4   4

2019-11-24-185457\2019-11-24-185457_0011
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[ -1  -1   0 ... -10 -10 -13]
 [ -1  -1   0 ... -10   0  -5]
 [ -1  -1  -1 ...   2 -12  -8]
 ...
 [  2   2   2 ... -11 -10 -15]
 [  1   1   1 ... -12 -12 -15]
 [  1   1   1 ...  -9 -11 -22]]
[[ -1  -1   0 ... -10 -10 -13]
 [ -1  -1   0 ... -10   0  -5]
 [ -1  -1  -1 ...   2 -12  -8]
 ...
 [  2   2   2 ... -11 -10 -15]
 [  1   1   1 ... -12 -12 -15]
 [  1   1   1 ...  -9 -11 -22]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0011.tif
2019-11-24-185457\2019-11-24-185457_0012
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[ -2  -1  -1 ... -13  -2 -15]
 [ -2  -1  -1 ...  -6  -2  -3]
 [ -2  -2  -2

2019-11-24-185457\2019-11-24-185457_0023
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[ -1  -1  -1 ... -11 -13 -18]
 [ -1  -1  -1 ...  -1  -3  -5]
 [ -1  -1  -1 ...  -9 -13 -13]
 ...
 [  1   1   1 ...  -5  -7 -17]
 [  0   0   0 ... -12  -3 -13]
 [  0   0  -1 ...  -3 -12 -14]]
[[ -1  -1  -1 ... -11 -13 -18]
 [ -1  -1  -1 ...  -1  -3  -5]
 [ -1  -1  -1 ...  -9 -13 -13]
 ...
 [  1   1   1 ...  -5  -7 -17]
 [  0   0   0 ... -12  -3 -13]
 [  0   0  -1 ...  -3 -12 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0023.tif
2019-11-24-185457\2019-11-24-185457_0024
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  2   2   2 ... -14 -10  -8]
 [  2   2   2 ... -12  -1   4]
 [  2   2   2

2019-11-24-185457\2019-11-24-185457_0035
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  4   4   5 ... -16 -13 -15]
 [  4   5   5 ...  -9  -3  -5]
 [  4   4   4 ... -11 -20  -7]
 ...
 [ -3  -3  -3 ... -10 -17 -27]
 [ -4  -4  -5 ... -15 -10 -20]
 [ -4  -4  -5 ... -18 -13 -22]]
[[  4   4   5 ... -16 -13 -15]
 [  4   5   5 ...  -9  -3  -5]
 [  4   4   4 ... -11 -20  -7]
 ...
 [ -3  -3  -3 ... -10 -17 -27]
 [ -4  -4  -5 ... -15 -10 -20]
 [ -4  -4  -5 ... -18 -13 -22]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0035.tif
2019-11-24-185457\2019-11-24-185457_0036
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  1   1   2 ...  -6 -10  -1]
 [  2   2   2 ...  -9   6   5]
 [  2   2   2

2019-11-24-185457\2019-11-24-185457_0047
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  3   4   4 ...  -7  -5  -5]
 [  3   4   4 ...  -7   6  -5]
 [  3   3   3 ...  -7  -8 -16]
 ...
 [ -1  -1  -1 ...   0 -11 -14]
 [ -2  -2  -2 ... -11  -9 -20]
 [ -2  -2  -2 ...  -2  -9 -14]]
[[  3   4   4 ...  -7  -5  -5]
 [  3   4   4 ...  -7   6  -5]
 [  3   3   3 ...  -7  -8 -16]
 ...
 [ -1  -1  -1 ...   0 -11 -14]
 [ -2  -2  -2 ... -11  -9 -20]
 [ -2  -2  -2 ...  -2  -9 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0047.tif
2019-11-24-185457\2019-11-24-185457_0048
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  3   3   4 ... -12 -22 -11]
 [  3   3   4 ...  -9   2  -8]
 [  3   3   3

2019-11-24-185457\2019-11-24-185457_0059
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  4   4   4 ...  -4  -8 -28]
 [  4   4   4 ...  -5  -4  -7]
 [  4   4   4 ...  -5 -10 -14]
 ...
 [  1   1   1 ...  -3 -11 -19]
 [  1   1   1 ...  -9  -9 -17]
 [  1   1   1 ...   2 -13 -18]]
[[  4   4   4 ...  -4  -8 -28]
 [  4   4   4 ...  -5  -4  -7]
 [  4   4   4 ...  -5 -10 -14]
 ...
 [  1   1   1 ...  -3 -11 -19]
 [  1   1   1 ...  -9  -9 -17]
 [  1   1   1 ...   2 -13 -18]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0059.tif
2019-11-24-185457\2019-11-24-185457_0060
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  3   4   4 ... -10 -15  -7]
 [  4   4   4 ...  -6  -7  -3]
 [  4   4   4

2019-11-24-185457\2019-11-24-185457_0071
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  3   3   4 ...  -2  -8 -19]
 [  3   3   3 ...  -9  -1  -5]
 [  3   3   3 ...  -2 -10 -12]
 ...
 [ -2  -2  -2 ...  -4 -11 -16]
 [ -3  -3  -3 ...  -6  -9 -20]
 [ -3  -3  -3 ...   0 -13 -16]]
[[  3   3   4 ...  -2  -8 -19]
 [  3   3   3 ...  -9  -1  -5]
 [  3   3   3 ...  -2 -10 -12]
 ...
 [ -2  -2  -2 ...  -4 -11 -16]
 [ -3  -3  -3 ...  -6  -9 -20]
 [ -3  -3  -3 ...   0 -13 -16]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0071.tif
2019-11-24-185457\2019-11-24-185457_0072
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  4   4   4 ...  -8 -13 -16]
 [  4   4   4 ...  -8   0  -2]
 [  4   4   4

2019-11-24-185457\2019-11-24-185457_0083
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  4   4   4 ... -13  -5 -10]
 [  4   4   4 ... -12  -2  -6]
 [  4   4   4 ...  -3  -5 -14]
 ...
 [  2   1   1 ...  -3  -5 -18]
 [  1   1   1 ...  -9  -8 -18]
 [  1   1   1 ...  -6  -3 -17]]
[[  4   4   4 ... -13  -5 -10]
 [  4   4   4 ... -12  -2  -6]
 [  4   4   4 ...  -3  -5 -14]
 ...
 [  2   1   1 ...  -3  -5 -18]
 [  1   1   1 ...  -9  -8 -18]
 [  1   1   1 ...  -6  -3 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0083.tif
2019-11-24-185457\2019-11-24-185457_0084
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  0   1   1 ... -12 -10 -10]
 [  1   1   1 ... -14   6  -9]
 [  1   1   1

2019-11-24-185457\2019-11-24-185457_0095
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  9   9   9 ...  -9 -17 -10]
 [  9   9   9 ...  -5   6  -1]
 [  9   9   9 ...  -7 -14 -11]
 ...
 [ -1  -1  -1 ...   0 -17 -21]
 [ -1  -1  -1 ...  -5  -5 -19]
 [ -1  -1  -1 ...  -1 -13 -13]]
[[  9   9   9 ...  -9 -17 -10]
 [  9   9   9 ...  -5   6  -1]
 [  9   9   9 ...  -7 -14 -11]
 ...
 [ -1  -1  -1 ...   0 -17 -21]
 [ -1  -1  -1 ...  -5  -5 -19]
 [ -1  -1  -1 ...  -1 -13 -13]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457\2019-11-24-185457_0095.tif
2019-11-24-185457\2019-11-24-185457_0096
2019-11-24-185457
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-185457
[[  3   3   3 ...  -7  -4 -16]
 [  3   3   3 ...  -1  -6  -5]
 [  3   3   3

2019-11-24-190350\2019-11-24-190350_0006
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -6  -5  -5 ... -10 -11  -5]
 [ -6  -5  -5 ... -20 -16  -9]
 [ -5  -5  -5 ... -11   2 -11]
 ...
 [  0   0   0 ...  -5   0   6]
 [  0   0   0 ...  -4 -11  -6]
 [  0  -1  -1 ...  -5 -18 -17]]
[[ -6  -5  -5 ... -10 -11  -5]
 [ -6  -5  -5 ... -20 -16  -9]
 [ -5  -5  -5 ... -11   2 -11]
 ...
 [  0   0   0 ...  -5   0   6]
 [  0   0   0 ...  -4 -11  -6]
 [  0  -1  -1 ...  -5 -18 -17]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0006.tif
2019-11-24-190350\2019-11-24-190350_0007
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -2  -2  -2 ... -11  -8  -5]
 [ -2  -2  -2 ... -10  -8  -3]
 [ -2  -1  -1

2019-11-24-190350\2019-11-24-190350_0018
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -3  -3  -4 ... -16 -12  -6]
 [ -3  -3  -3 ... -12  -8 -11]
 [ -3  -3  -3 ...  -2  -4 -11]
 ...
 [  3   3   3 ... -17   4   1]
 [  2   2   2 ...  -5  -6   3]
 [  2   2   1 ...  -3  -7 -23]]
[[ -3  -3  -4 ... -16 -12  -6]
 [ -3  -3  -3 ... -12  -8 -11]
 [ -3  -3  -3 ...  -2  -4 -11]
 ...
 [  3   3   3 ... -17   4   1]
 [  2   2   2 ...  -5  -6   3]
 [  2   2   1 ...  -3  -7 -23]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0018.tif
2019-11-24-190350\2019-11-24-190350_0019
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -2  -2  -2 ... -13  -5  -9]
 [ -2  -2  -2 ...  -9 -15  -3]
 [ -2  -2  -2

2019-11-24-190350\2019-11-24-190350_0030
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -6  -6  -6 ... -29  -2 -13]
 [ -6  -6  -6 ... -14 -16 -13]
 [ -5  -5  -5 ...  -5  -8 -18]
 ...
 [ -1  -1   0 ...  -9   3  -2]
 [  0   0   0 ...  -3 -11 -11]
 [  0   0   0 ...  -6 -15 -22]]
[[ -6  -6  -6 ... -29  -2 -13]
 [ -6  -6  -6 ... -14 -16 -13]
 [ -5  -5  -5 ...  -5  -8 -18]
 ...
 [ -1  -1   0 ...  -9   3  -2]
 [  0   0   0 ...  -3 -11 -11]
 [  0   0   0 ...  -6 -15 -22]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0030.tif
2019-11-24-190350\2019-11-24-190350_0031
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -3  -3  -2 ...  -7 -10   2]
 [ -3  -3  -3 ...  -9 -17  -4]
 [ -3  -3  -3

2019-11-24-190350\2019-11-24-190350_0042
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[  1   2   2 ... -15  -8  14]
 [  1   1   2 ...  -5 -10   2]
 [  1   1   1 ...  -5  -5  -7]
 ...
 [  0   0   0 ...  -7  -6   0]
 [  0  -1  -1 ...  -8  -8  -4]
 [ -1  -1  -2 ...  -9  -9 -16]]
[[  1   2   2 ... -15  -8  14]
 [  1   1   2 ...  -5 -10   2]
 [  1   1   1 ...  -5  -5  -7]
 ...
 [  0   0   0 ...  -7  -6   0]
 [  0  -1  -1 ...  -8  -8  -4]
 [ -1  -1  -2 ...  -9  -9 -16]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0042.tif
2019-11-24-190350\2019-11-24-190350_0043
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -3  -3  -3 ... -25  -1  -9]
 [ -3  -3  -3 ... -24  -5   1]
 [ -3  -3  -3

2019-11-24-190350\2019-11-24-190350_0054
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -4  -4  -4 ... -17   0  -1]
 [ -4  -4  -4 ... -21 -11  -9]
 [ -4  -4  -4 ...  -5  -2  -4]
 ...
 [  1   1   1 ...  -1  -3   0]
 [  1   1   1 ...  -3  -7   0]
 [  1   1   1 ...  -7 -13 -16]]
[[ -4  -4  -4 ... -17   0  -1]
 [ -4  -4  -4 ... -21 -11  -9]
 [ -4  -4  -4 ...  -5  -2  -4]
 ...
 [  1   1   1 ...  -1  -3   0]
 [  1   1   1 ...  -3  -7   0]
 [  1   1   1 ...  -7 -13 -16]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0054.tif
2019-11-24-190350\2019-11-24-190350_0055
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -4  -4  -4 ... -15 -11   0]
 [ -4  -4  -4 ... -14 -14  -5]
 [ -4  -4  -4

2019-11-24-190350\2019-11-24-190350_0066
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -6  -6  -6 ... -22 -12  -7]
 [ -6  -6  -6 ... -10 -12 -11]
 [ -5  -5  -5 ...   0   2  -7]
 ...
 [  2   2   2 ...   1 -10  -4]
 [  2   1   1 ...  -5  -8   0]
 [  2   1   1 ... -10 -10 -15]]
[[ -6  -6  -6 ... -22 -12  -7]
 [ -6  -6  -6 ... -10 -12 -11]
 [ -5  -5  -5 ...   0   2  -7]
 ...
 [  2   2   2 ...   1 -10  -4]
 [  2   1   1 ...  -5  -8   0]
 [  2   1   1 ... -10 -10 -15]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0066.tif
2019-11-24-190350\2019-11-24-190350_0067
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -6  -6  -6 ... -21  -4 -10]
 [ -7  -6  -6 ... -29 -13  -8]
 [ -6  -6  -6

2019-11-24-190350\2019-11-24-190350_0078
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -5  -5  -5 ... -13   5  -8]
 [ -5  -5  -5 ... -12 -12  -4]
 [ -5  -5  -5 ...  -8   3 -17]
 ...
 [  0   0   0 ...  -1   9  -2]
 [  0   0   0 ...  -4  -4  -1]
 [  1   1   0 ...  -5 -10 -13]]
[[ -5  -5  -5 ... -13   5  -8]
 [ -5  -5  -5 ... -12 -12  -4]
 [ -5  -5  -5 ...  -8   3 -17]
 ...
 [  0   0   0 ...  -1   9  -2]
 [  0   0   0 ...  -4  -4  -1]
 [  1   1   0 ...  -5 -10 -13]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0078.tif
2019-11-24-190350\2019-11-24-190350_0079
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -6  -5  -5 ... -14  -7  -3]
 [ -6  -6  -5 ... -25 -21  -8]
 [ -5  -5  -5

2019-11-24-190350\2019-11-24-190350_0090
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -4  -4  -4 ... -19   0   1]
 [ -4  -4  -4 ... -12 -13   1]
 [ -4  -4  -4 ...  -5  -1 -10]
 ...
 [ -3  -3  -3 ...   6   0   4]
 [ -3  -3  -4 ...   2  -6  -5]
 [ -3  -4  -4 ... -11 -11 -14]]
[[ -4  -4  -4 ... -19   0   1]
 [ -4  -4  -4 ... -12 -13   1]
 [ -4  -4  -4 ...  -5  -1 -10]
 ...
 [ -3  -3  -3 ...   6   0   4]
 [ -3  -3  -4 ...   2  -6  -5]
 [ -3  -4  -4 ... -11 -11 -14]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350\2019-11-24-190350_0090.tif
2019-11-24-190350\2019-11-24-190350_0091
2019-11-24-190350
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-190350
[[ -5  -5  -5 ... -24 -10  -1]
 [ -5  -5  -5 ... -20 -16 -16]
 [ -5  -5  -5

2019-11-24-191423\2019-11-24-191423_0001
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -2  -2  -2 ...  -5 -11  -9]
 [ -2  -2  -2 ... -18  -3 -15]
 [ -3  -3  -2 ...  -4  -8  -8]
 ...
 [ -7  -8  -8 ... -17 -18 -14]
 [ -8  -8  -8 ... -11 -11 -14]
 [ -8  -8  -8 ... -15  -9 -18]]
[[ -2  -2  -2 ...  -5 -11  -9]
 [ -2  -2  -2 ... -18  -3 -15]
 [ -3  -3  -2 ...  -4  -8  -8]
 ...
 [ -7  -8  -8 ... -17 -18 -14]
 [ -8  -8  -8 ... -11 -11 -14]
 [ -8  -8  -8 ... -15  -9 -18]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0001.tif
2019-11-24-191423\2019-11-24-191423_0002
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  1   2   3 ...  -5 -11 -18]
 [  1   2   2 ...  -8 -10 -16]
 [  0   1   1

2019-11-24-191423\2019-11-24-191423_0013
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  4   4   5 ... -10 -16 -10]
 [  4   4   4 ... -24  -8 -24]
 [  3   3   4 ...  -6 -11 -13]
 ...
 [ -3  -3  -3 ... -15 -17 -14]
 [ -3  -3  -3 ...  -9 -13  -9]
 [ -4  -3  -3 ...  -9 -10 -16]]
[[  4   4   5 ... -10 -16 -10]
 [  4   4   4 ... -24  -8 -24]
 [  3   3   4 ...  -6 -11 -13]
 ...
 [ -3  -3  -3 ... -15 -17 -14]
 [ -3  -3  -3 ...  -9 -13  -9]
 [ -4  -3  -3 ...  -9 -10 -16]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0013.tif
2019-11-24-191423\2019-11-24-191423_0014
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  1   1   2 ...  -6  -8 -22]
 [  1   1   2 ... -23  -2 -28]
 [  0   0   0

2019-11-24-191423\2019-11-24-191423_0025
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -5  -5  -5 ... -11  -4 -20]
 [ -5  -5  -5 ... -21  -5 -19]
 [ -5  -5  -5 ...  -4  -9  -7]
 ...
 [-10 -10 -10 ... -11 -11 -12]
 [-10 -11 -11 ... -16 -16  -5]
 [-10 -10 -11 ... -15 -12 -11]]
[[ -5  -5  -5 ... -11  -4 -20]
 [ -5  -5  -5 ... -21  -5 -19]
 [ -5  -5  -5 ...  -4  -9  -7]
 ...
 [-10 -10 -10 ... -11 -11 -12]
 [-10 -11 -11 ... -16 -16  -5]
 [-10 -10 -11 ... -15 -12 -11]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0025.tif
2019-11-24-191423\2019-11-24-191423_0026
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -1  -1  -1 ... -11 -13 -18]
 [ -1  -1  -1 ... -11  -1 -19]
 [ -1  -1  -1

2019-11-24-191423\2019-11-24-191423_0037
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -3  -3  -3 ...  -8  -9 -20]
 [ -3  -3  -3 ... -22  -3 -20]
 [ -3  -3  -3 ...  -2 -15  -8]
 ...
 [ -5  -5  -5 ... -20 -23 -10]
 [ -6  -6  -6 ... -13 -24  -5]
 [ -6  -6  -6 ... -14 -16 -22]]
[[ -3  -3  -3 ...  -8  -9 -20]
 [ -3  -3  -3 ... -22  -3 -20]
 [ -3  -3  -3 ...  -2 -15  -8]
 ...
 [ -5  -5  -5 ... -20 -23 -10]
 [ -6  -6  -6 ... -13 -24  -5]
 [ -6  -6  -6 ... -14 -16 -22]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0037.tif
2019-11-24-191423\2019-11-24-191423_0038
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -1  -1  -1 ...  -4 -11  -9]
 [ -1  -1   0 ... -20   5 -16]
 [ -1  -1  -1

2019-11-24-191423\2019-11-24-191423_0049
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -1   0   0 ... -11 -15 -13]
 [ -1  -1   0 ... -12  -6 -14]
 [ -2  -1  -1 ... -12 -15 -17]
 ...
 [ -9  -9  -9 ... -17 -17 -16]
 [-10 -10 -10 ... -14 -13 -12]
 [-10 -10 -10 ... -14 -11 -19]]
[[ -1   0   0 ... -11 -15 -13]
 [ -1  -1   0 ... -12  -6 -14]
 [ -2  -1  -1 ... -12 -15 -17]
 ...
 [ -9  -9  -9 ... -17 -17 -16]
 [-10 -10 -10 ... -14 -13 -12]
 [-10 -10 -10 ... -14 -11 -19]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0049.tif
2019-11-24-191423\2019-11-24-191423_0050
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  2   2   2 ...   0 -20  -7]
 [  1   2   2 ... -32  -3 -15]
 [  1   1   1

2019-11-24-191423\2019-11-24-191423_0061
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  0   0   1 ...  -4 -21  -8]
 [  0   1   1 ... -23  -5 -13]
 [  0   0   0 ...  -5 -10  -7]
 ...
 [ -3  -3  -3 ... -21 -21 -10]
 [ -3  -3  -3 ... -13 -18 -10]
 [ -3  -3  -3 ...  -8 -13 -18]]
[[  0   0   1 ...  -4 -21  -8]
 [  0   1   1 ... -23  -5 -13]
 [  0   0   0 ...  -5 -10  -7]
 ...
 [ -3  -3  -3 ... -21 -21 -10]
 [ -3  -3  -3 ... -13 -18 -10]
 [ -3  -3  -3 ...  -8 -13 -18]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0061.tif
2019-11-24-191423\2019-11-24-191423_0062
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  4   4   5 ... -14 -10  -5]
 [  4   4   4 ... -17 -13 -25]
 [  3   3   4

2019-11-24-191423\2019-11-24-191423_0073
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -3  -3  -3 ... -21 -23 -27]
 [ -3  -3  -3 ... -21  -9 -17]
 [ -3  -3  -3 ... -10 -13  -7]
 ...
 [ -6  -6  -6 ... -19 -23  -8]
 [ -7  -7  -7 ... -21 -22 -10]
 [ -7  -7  -7 ...  -9 -15 -19]]
[[ -3  -3  -3 ... -21 -23 -27]
 [ -3  -3  -3 ... -21  -9 -17]
 [ -3  -3  -3 ... -10 -13  -7]
 ...
 [ -6  -6  -6 ... -19 -23  -8]
 [ -7  -7  -7 ... -21 -22 -10]
 [ -7  -7  -7 ...  -9 -15 -19]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0073.tif
2019-11-24-191423\2019-11-24-191423_0074
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -2  -1  -1 ... -13 -17 -10]
 [ -1  -1  -1 ... -28  -1 -24]
 [ -1  -1  -1

2019-11-24-191423\2019-11-24-191423_0085
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -2  -2  -2 ... -11 -17  -2]
 [ -2  -2  -2 ... -20  -1 -24]
 [ -2  -2  -2 ...  -5 -14 -11]
 ...
 [ -7  -7  -7 ... -17 -21  -4]
 [ -7  -7  -7 ... -16 -24 -13]
 [ -7  -8  -8 ...  -9 -16 -10]]
[[ -2  -2  -2 ... -11 -17  -2]
 [ -2  -2  -2 ... -20  -1 -24]
 [ -2  -2  -2 ...  -5 -14 -11]
 ...
 [ -7  -7  -7 ... -17 -21  -4]
 [ -7  -7  -7 ... -16 -24 -13]
 [ -7  -8  -8 ...  -9 -16 -10]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0085.tif
2019-11-24-191423\2019-11-24-191423_0086
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[  0   0   1 ...  -6 -26 -11]
 [  0   1   1 ... -24   5 -23]
 [  0   0   0

2019-11-24-191423\2019-11-24-191423_0097
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -4  -4  -3 ... -17 -18 -20]
 [ -4  -3  -3 ... -25 -11 -18]
 [ -4  -4  -4 ... -10 -10 -11]
 ...
 [ -9  -9  -9 ... -20 -16 -10]
 [ -9  -9 -10 ... -18 -20 -16]
 [ -9 -10 -10 ...  -9 -13 -11]]
[[ -4  -4  -3 ... -17 -18 -20]
 [ -4  -3  -3 ... -25 -11 -18]
 [ -4  -4  -4 ... -10 -10 -11]
 ...
 [ -9  -9  -9 ... -20 -16 -10]
 [ -9  -9 -10 ... -18 -20 -16]
 [ -9 -10 -10 ...  -9 -13 -11]]
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423\2019-11-24-191423_0097.tif
2019-11-24-191423\2019-11-24-191423_0098
2019-11-24-191423
E:\hl585\duncan_data_processed\3ded_kenneth_harris_samples\191123_med_kdmh\bismuth_susalicylate_B_20191124_175237\2019-11-24-191423
[[ -1   0   0 ...  -1 -20 -17]
 [ -1  -1   0 ... -16  -6 -19]
 [ -2  -2  -1